apiVersion: apps/v1
kind: Deployment
metadata:
  name: bug #The name of the Kubernetes Deployment to be created in the Kubernetes cluster
  labels:
    app: bug
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: bug
  template:
    metadata:
      labels:
        app: bug
    spec:
      containers:
        - name: bug #The name of the container
          image: alvonellos/bug:$BUILD_NUMBER #The Docker image
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
              hostPort: 8085
              hostIP: 0.0.0.0
              protocol: "TCP"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: TOKEN

