apiVersion: v1
kind: Service
metadata:
  name: bug #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: bug
  type: LoadBalancer #Type of the Kubernetes Service
  externalIPs:
    - 172.16.253.4
  loadBalancerIP: 172.16.253.4
  ports:
    - port: 80 #Service port
      targetPort: 8004
      protocol: TCP #The port for the container