apiVersion: v1
kind: Service
metadata:
  name: bug #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: bug
  type: LoadBalancer #Type of the Kubernetes Service
  externalIPs:
    - 192.168.0.75
  loadBalancerIP: 192.168.0.75
  ports:
    - port: 80 #Service port
      targetPort: 8085
      protocol: TCP #The port for the container